name: AWS Lambda - Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar QEMU para arm64
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Configurar binfmt
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Instalar dependências e build
        env:
          CI: true
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_NAME: ${{ secrets.ADMIN_NAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run: |
          npm install
          npx prisma generate
          npm run build
          rm -rf src
          mv build src
          npm ci --omit=dev

      - name: Criar pacote de deploy
        run: zip -r deploy.zip ./*

      - name: Deploy para AWS Lambda
        run: |
          aws lambda update-function-code --function-name=blog-api --zip-file=fileb://deploy.zip
