name: AWS Lambda - Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar QEMU para arm64
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64

      - name: Configurar binfmt
        run: |
          sudo apt-get update
          sudo apt-get install -y binfmt-support qemu-user-static

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "22"
          architecture: "arm64"

      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: npm install
        env:
          CI: true
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_NAME: ${{ secrets.ADMIN_NAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run: |
          npm install
          npx prisma generate
          npm run build
          rm -rf src
          mv build src
          npm install --omit=dev

      - name: deploy
        run: |
          zip -r deploy.zip ./*
          aws lambda update-function-code --function-name=blog-api --zip-file=fileb://deploy.zip
