name: AWS Lambda - Deploy

on:
  push:
    branches:
      - master

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run seed in Docker
        env:
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_NAME: ${{ secrets.ADMIN_NAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          docker run --rm \
            -v $(pwd):/app \
            -w /app \
            -e ADMIN_EMAIL \
            -e ADMIN_NAME \
            -e ADMIN_PASSWORD \
            -e DATABASE_URL \
            node:22 \
            sh -c "npm install && npx prisma generate && npm run seed"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "22"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
      - name: Prepare build
        run: |
          npm install
          PRISMA_CLI_BINARY_TARGETS=linux-arm64-openssl-3.0.x npx prisma generate
          npm run build
          rm -rf src
          mv build src
          npm install --omit=dev
      - name: Deploy to AWS Lambda
        run: |
          zip -r deploy.zip ./*
          aws lambda update-function-code --function-name=blog-api --zip-file=fileb://deploy.zip
