name: AWS Lambda - Deploy

on:
  push:
    branches:
    - master   

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:  
          node-version: '22'

      - name: Configure AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
      - name: Build Docker image
        run: |
          docker build -t blog-api .
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_ENDPOINT }}
      - name: Tag Docker image
        run: |
          docker tag blog-api:latest ${{ secrets.ECR_REPOSITORY_URI }}:latest
      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest
