name: AWS Lambda - Deploy

on:
  push:
    branches:
    - master   

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:  
          node-version: '22'
      - name: Configure AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
      - name: npm install
        env:
          CI: true
        run: |
          npm install
          npm run build
          rm -rf src
          mv build src
          npx prisma generate
          npm install --omit=dev
      - name: deploy
        run: |
          zip -r deploy.zip ./*
          aws lambda update-function-code --function-name=blog-api --zip-file=fileb://deploy.zip 
